### ISSUE TITLE
May I get the code for pose keypoint propagation on JHMDB?

### ISSUE THREAD

**Issue by hscha** [xiaolonw/TimeCycle#11]
Source codes for VLOG and Davis are helpful to reproduce results on the datasets.

May I get the source code for JHMDB task?

**Comment by cinjon** [comment]
Bumping this.

**Comment by xiaolonw** [comment]
will try to do it when free ... just being extremely busy these days ... the test code is very similar to the davis one though ... but releasing data processing/dataloader/test code together needs work ...
