### ISSUE TITLE
Reproducing DeepCluster DAVIS Evaluation Results

### ISSUE THREAD

**Issue by dmckee5** [xiaolonw/TimeCycle#14]
Hello,

Thank you for providing this repo! I have had some trouble reproducing the exact DeepCluster performance numbers on DAVIS-2017 from your paper. Could you confirm whether the network you used is the VGG16-PyTorch pretrained model from the DeepCluster repo (https://github.com/facebookresearch/deepcluster)? 

In addition, during evaluation do you extract the feature map directly before maxpool-4 in the VGG16 model, or which feature map output do you use from the pretrained model?

Thanks!

**Comment by ajabri** [comment]
Hi @dmckee5 -- we did indeed use the pretrained VGG16 model from the deepcluster repo. The only modification is to remove the last two pooling layers (maxpool4 and maxpool5?); this should yield a feature map of dimension 30x30 for an input of 240x240.

**Comment by dmckee5** [comment]
Sorry forgot to close this issue. Thanks for your help @ajabri!
