### ISSUE TITLE
AffineGridGenV3

### ISSUE THREAD

**Issue by cinjon** [xiaolonw/TimeCycle#15]
What is the reason for AffineGridGenV3? It seems like the only change from it and V2 was that you moved the creation of the grids to the forward pass instead of the initialization and made them Tensors instead of FloatTensors. What was the reasoning behind these changes?

**Comment by xiaolonw** [comment]
So the function of V3 is still the same as V2. 

The reason of making a V3 is that defining new tensors in __init__ does not work together with the CycleTime class, when we try to make AffineGridGenV3 as part of the function in CycleTime.
