### ISSUE TITLE
Can not open model file

### ISSUE THREAD

**Issue by olojuwin** [xiaolonw/TimeCycle#21]
Can you provide Baidu Cloud Link?I'd download from google drive,but i can't open it

**Comment by nkalavak** [comment]
Hi, were you able to access the model file? I am running into the same issue

**Comment by olojuwin** [comment]
Hi,I opened it successfully。You can use it directly like any other model！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Niveditha Kalavakonda"<notifications@github.com&gt;; 
发送时间: 2020年1月16日(星期四) 凌晨3:45
收件人: "xiaolonw/TimeCycle"<TimeCycle@noreply.github.com&gt;; 
抄送: "朱望"<502401452@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [xiaolonw/TimeCycle] Can not open model file (#21)




Hi, were you able to access the model file? I am running into the same issue
