### ISSUE TITLE
Trained model cannot download now.

### ISSUE THREAD

**Issue by logic1988** [xiaolonw/TimeCycle#3]
download model from https://www.dropbox.com/s/txsj62dp9nuxs6h/checkpoint_14.pth.tar?dl=0  failed as:
Too many requests
Sorry, this link has been automatically turned off for now. Learn more about traffic limits.

**Comment by xiaolonw** [comment]
Sorry about that, I have replaced the link with google drive:
https://drive.google.com/file/d/1jKwP6qOoEFhhr9WFL_mfXvk0IHtElsmB/view?usp=sharing
