### ISSUE TITLE
In test_davis.py line 459

### ISSUE THREAD

**Issue by Talegqz** [xiaolonw/TimeCycle#4]
Should "hid = ids / width_dim  " be "hid = ids / /width_dim" ?  Otherwise the hid is not int, then you can not use it as the index.

**Comment by xiaolonw** [comment]
as both ids and width_dim are int, the output by using / is also int

**Comment by LuoweiZhou** [comment]
@xiaolonw which version of python and pytorch are you using

**Comment by xiaolonw** [comment]
I am actually using python 2 and pytorch 0.4 
but i have tried it with pytorch 1.0 as well

**Comment by LuoweiZhou** [comment]
I tested it on python 3.6 + pytorch 1.0 and have not seen any issue so far besides the minor one mentioned by @Talegqz

**Comment by xiaolonw** [comment]
I have fixed it in the code. Thank you guys for bringing it up!
