### ISSUE TITLE
Error while converting checkpoint_14.pth.tar model 

### ISSUE THREAD

**Issue by lathampratti** [xiaolonw/TimeCycle#6]
The following error is hit while converting the released model (checkpoint_14.pth.tar) to resnet50. 

```
KeyError                                  Traceback (most recent call last)
<ipython-input-3-6df704e20364> in <module>()
     15     kk = k.replace('module.encoderVideo.', '')
     16     tmp = model_state[k]
---> 17     if net_state[kk].shape != model_state[k].shape and net_state[kk].dim() == 4 and model_state[k].dim() == 5:
     18         tmp = model_state[k].squeeze(2)
     19     net_state[kk][:] = tmp[:]

KeyError: 'conv1.weight'
```

Do I need a specific version of pytorch to convert the model?

**Comment by xiaolonw** [comment]
Sorry about that. This is a bug, it has been fixed now.
Basically "net = nn.Sequential(*list(net.children())[:-3])" should be put after loading the dictionary.

**Comment by lathampratti** [comment]
Thanks! That resolved the issue.
