### ISSUE TITLE
How many GPU memory it Need?

### ISSUE THREAD

**Issue by dongfangduoshou123** [xiaolonw/TimeCycle#7]
Hi,
  I run test_davis.py,  It always report CUDA out of memory, My GPU has 6GB, it is not enough?
I set the batch_size=1, it also report CUDA out of memory, why?

And if you could add a demo to run tracking on general video, it well be fine, thank you!

**Comment by xiaolonw** [comment]
I think it takes more than 6GB.

**Comment by dongfangduoshou123** [comment]
Is it because in One batch_size, it not just contains one image, but all the images in one of the  image folder,  may be one image folder contains for example 80 images, right?

I want to know, is it possible to give a bounding box of video's first frame as the TimeCycle algorithm's input, let timeCycle to track the target in the bounding box?

thank you!

**Comment by swrdZWJ** [comment]
**I want to know, is it possible to give a bounding box of video's first frame as the TimeCycle algorithm's input, let timeCycle to track the target in the bounding box?**

I am also interested in this question，Have you tested it so far？thank you ：）  @dongfangduoshou123   @xiaolonw
